=== barracuda156/BoCA/doc/dtds/component.dtd
<!-- BoCA component XML description DTD -->

<!ENTITY % BoCA.Version "-//DTD BoCA 1.0 Draft//EN">

<!ELEMENT component (name, version, id, type, format*, external?)>

	<!ELEMENT name (#PCDATA)>
	<!ELEMENT version (#PCDATA)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT type (#PCDATA)>

	<!ELEMENT format (name, extension+)>

		<!ELEMENT extension (#PCDATA)>

	<!ELEMENT external (command, arguments, mode, (informat?, outformat?), tag*, parameters?)>

		<!ELEMENT command (#PCDATA)>
		<!ELEMENT arguments (#PCDATA)>
		<!ELEMENT mode (#PCDATA)>
		<!ELEMENT informat (#PCDATA)>
		<!ELEMENT outformat (#PCDATA)>

		<!ELEMENT tag (#PCDATA)>
		<!ATTLIST tag mode CDATA #REQUIRED>

		<!ELEMENT parameters (switch | selection | range)*>

			<!ELEMENT switch (#PCDATA)>
			<!ATTLIST switch name	  CDATA	  #REQUIRED
					 argument CDATA	  #REQUIRED
					 enabled  NMTOKEN #IMPLIED>

			<!ELEMENT selection (option+)>
			<!ATTLIST selection name     CDATA   #REQUIRED
					    argument CDATA   #REQUIRED
					    enabled  NMTOKEN #IMPLIED
					    default  NMTOKEN #IMPLIED>

				<!ELEMENT option (#PCDATA)>
				<!ATTLIST option alias CDATA #IMPLIED>

			<!ELEMENT range (min, max)>
			<!ATTLIST range name	 CDATA	 #REQUIRED
					argument CDATA	 #REQUIRED
					enabled	 NMTOKEN #IMPLIED
					default	 NMTOKEN #IMPLIED
					step	 NMTOKEN #IMPLIED>

				<!ELEMENT min (#PCDATA)>
				<!ATTLIST min alias CDATA #IMPLIED>

				<!ELEMENT max (#PCDATA)>
				<!ATTLIST max alias CDATA #IMPLIED>

=== barracuda156/BoCA/bin64/boca_decoder_vorbis.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>Ogg Vorbis Decoder</name>
  <version>1.0</version>
  <id>vorbiscmd-in</id>
  <type>decoder</type>
  <format>
    <name>Ogg Vorbis Audio</name>
    <extension>ogg</extension>
    <tag mode="other">VorbisComment</tag>
  </format>
  <external>
    <command>codecs/cmdline/oggdec.exe</command>
    <arguments>%OPTIONS %INFILE --stdout</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <parameters>
      <switch name="Downmix multi-channel audio to stereo" argument="--downmix"/>
      <selection name="Dither output" argument="--dither %VALUE">
	<option alias="Without noise shaping">1</option>
 	<option alias="With light noise shaping">2</option>
 	<option alias="With medium noise shaping">3</option>
 	<option alias="With heavy noise shaping">4</option>
      </selection>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/scripts/unix/boca_encoder_wavpack.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>WavPack Lossless Compressor</name>
  <version>1.0</version>
  <id>wv-out</id>
  <type>encoder</type>
  <format>
    <name>WavPack Files</name>
    <extension>wv</extension>
    <tag id="apev2-tag" mode="append">APEv2</tag>
  </format>
  <external>
    <command>/usr/bin/wavpack</command>
    <arguments>-i -m %OPTIONS - -o %OUTFILE</arguments>
    <mode>stdio</mode>
    <informat>wave</informat>
    <parameters>
      <range name="Enable hybrid compression" argument="-b%VALUE" default="256" step="8">
	<min alias="64 kbps">64</min>
	<max alias="720 kbps">720</max>
      </range>
      <selection name="Compression mode" argument="%VALUE" default="-h">
	<option alias="Fast">-f</option>
	<option alias="High quality">-h</option>
	<option alias="Very high quality">-hh</option>
      </selection>
      <range name="Extra encode processing" argument="-x%VALUE" default="1">
	<min alias="faster">1</min>
	<max alias="better">6</max>
      </range>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/bin/boca_decoder_speex.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>Speex Speech Decoder</name>
  <version>1.0</version>
  <id>speexcmd-in</id>
  <type>decoder</type>
  <format>
    <name>Speex Files</name>
    <extension>spx</extension>
    <tag mode="other">VorbisComment</tag>
  </format>
  <external>
    <command>codecs/cmdline/speexdec.exe</command>
    <arguments>%OPTIONS %INFILE %OUTFILE</arguments>
    <mode>file</mode>
    <outformat>wave</outformat>
    <parameters>
      <switch name="Disable perceptual enhancements" argument="--no-enh"/>
      <selection name="Force decoding mode" argument="%VALUE">
	<option alias="Narrowband">--force-nb</option>
	<option alias="Wideband">--force-wb</option>
	<option alias="Ultra-wideband">--force-uwb</option>
      </selection>
      <selection name="Force channels" argument="%VALUE">
	<option alias="Mono">--mono</option>
	<option alias="Stereo">--stereo</option>
      </selection>
      <selection name="Force sampling rate" argument="--rate %VALUE">
	<option>8000</option>
	<option>11025</option>
	<option>12000</option>
	<option>16000</option>
	<option>22050</option>
	<option>24000</option>
	<option>32000</option>
	<option>44100</option>
	<option>48000</option>
      </selection>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/scripts/boca_decoder_ffmpeg_dsd.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Digital Stream Digital Decoder</name>
  <version>1.0</version>
  <id>ffmpeg-dsd-dec</id>
  <type>decoder</type>
  <format>
    <name>DSD Files</name>
    <extension>dsf</extension>
    <extension>dff</extension>
  </format>
  <external>
    <command>ffmpeg</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== barracuda156/BoCA/bin64/boca_encoder_optimfrog.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>OptimFROG Audio Encoder</name>
  <version>1.0</version>
  <id>ofr-out</id>
  <type>encoder</type>
  <format>
    <name>OptimFROG Files</name>
    <extension>ofr</extension>
    <tag mode="append">APEv2</tag>
  </format>
  <external>
    <command>codecs/cmdline/ofr.exe</command>
    <arguments>--encode %OPTIONS %INFILE --output %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
    <parameters>
      <selection name="Encoding mode" argument="--mode %VALUE" default="normal">
	<option alias="Fast">fast</option>
	<option alias="Normal">normal</option>
	<option alias="High">high</option>
	<option alias="Extra">extra</option>
	<option alias="Best">best</option>
	<option alias="High, new">highnew</option>
	<option alias="Extra, new">extranew</option>
	<option alias="Best, new">bestnew</option>
      </selection>
      <switch name="Store MD5 of original PCM data" argument="--md5" enabled="true"/>
      <switch name="Add recovery information to files" argument="--recovery"/>
      <selection name="Seeking" argument="--seek %VALUE" default="normal">
	<option alias="Fast">fast</option>
	<option alias="Normal">normal</option>
	<option alias="Slow">slow</option>
	<option alias="Minimum">min</option>
      </selection>
      <selection name="Optimization" argument="--optimize %VALUE" default="fast">
	<option alias="Disabled">none</option>
	<option alias="Fast">fast</option>
	<option alias="Normal">normal</option>
	<option alias="High">high</option>
	<option alias="Best">best</option>
      </selection>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/scripts/boca_encoder_ffmpeg_wma.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Windows Media Audio Encoder</name>
  <version>1.0</version>
  <id>ffmpeg-wma-out</id>
  <type>encoder</type>
  <format>
    <name>Windows Media Audio Files</name>
    <extension>wma</extension>
    <tag id="wma-tag" mode="other">WMA Metadata</tag>
  </format>
  <external>
    <command>ffmpeg</command>
    <arguments>-f wav -i %INFILE -acodec wmav2 %OPTIONS %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
    <parameters>
      <range name="Bitrate" argument="-ab %VALUE000" default="192" enabled="true" step="4">
	<min alias="24 kbps">24</min>
	<max alias="320 kbps">320</max>
      </range>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/scripts/macosx/boca_decoder_wavpack.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>WavPack Lossless Decompressor</name>
  <version>1.0</version>
  <id>wv-in</id>
  <type>decoder</type>
  <format>
    <name>WavPack Files</name>
    <extension>wv</extension>
    <tag id="apev2-tag" mode="append">APEv2</tag>
  </format>
  <external>
    <command ignoreExitCode="true">wvunpack</command>
    <arguments>%OPTIONS %INFILE -o -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== barracuda156/BoCA/bin64/boca_encoder_twolame.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>TwoLAME MP2 Encoder</name>
  <version>1.0</version>
  <id>twolame-out</id>
  <type>encoder</type>
  <format>
    <name>MPEG Audio Layer 2</name>
    <extension>mp2</extension>
  </format>
  <external>
    <command>codecs/cmdline/twolame.exe</command>
    <arguments>%OPTIONS %INFILE %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>
