=== barracuda156/BoCA/doc/dtds/component.dtd
<!-- BoCA component XML description DTD -->

<!ENTITY % BoCA.Version "-//DTD BoCA 1.0 Draft//EN">

<!ELEMENT component (name, version, id, type, format*, external?)>

	<!ELEMENT name (#PCDATA)>
	<!ELEMENT version (#PCDATA)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT type (#PCDATA)>

	<!ELEMENT format (name, extension+)>

		<!ELEMENT extension (#PCDATA)>

	<!ELEMENT external (command, arguments, mode, (informat?, outformat?), tag*, parameters?)>

		<!ELEMENT command (#PCDATA)>
		<!ELEMENT arguments (#PCDATA)>
		<!ELEMENT mode (#PCDATA)>
		<!ELEMENT informat (#PCDATA)>
		<!ELEMENT outformat (#PCDATA)>

		<!ELEMENT tag (#PCDATA)>
		<!ATTLIST tag mode CDATA #REQUIRED>

		<!ELEMENT parameters (switch | selection | range)*>

			<!ELEMENT switch (#PCDATA)>
			<!ATTLIST switch name	  CDATA	  #REQUIRED
					 argument CDATA	  #REQUIRED
					 enabled  NMTOKEN #IMPLIED>

			<!ELEMENT selection (option+)>
			<!ATTLIST selection name     CDATA   #REQUIRED
					    argument CDATA   #REQUIRED
					    enabled  NMTOKEN #IMPLIED
					    default  NMTOKEN #IMPLIED>

				<!ELEMENT option (#PCDATA)>
				<!ATTLIST option alias CDATA #IMPLIED>

			<!ELEMENT range (min, max)>
			<!ATTLIST range name	 CDATA	 #REQUIRED
					argument CDATA	 #REQUIRED
					enabled	 NMTOKEN #IMPLIED
					default	 NMTOKEN #IMPLIED
					step	 NMTOKEN #IMPLIED>

				<!ELEMENT min (#PCDATA)>
				<!ATTLIST min alias CDATA #IMPLIED>

				<!ELEMENT max (#PCDATA)>
				<!ATTLIST max alias CDATA #IMPLIED>

=== barracuda156/BoCA/bin64/boca_encoder_tta.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>TTA Lossless Audio Encoder</name>
  <version>1.0</version>
  <id>tta-out</id>
  <type>encoder</type>
  <format>
    <name>TTA Audio Files</name>
    <extension>tta</extension>
    <tag mode="prepend">ID3v2</tag>
  </format>
  <external>
    <command>codecs/cmdline/ttaenc.exe</command>
    <arguments>-e %OPTIONS %INFILE -o %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>

=== barracuda156/BoCA/scripts/boca_encoder_waon.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>WaoN MIDI Notes Writer</name>
  <version>1.0</version>
  <id>waon-enc</id>
  <type>encoder</type>
  <format>
    <name>MIDI Files</name>
    <extension>mid</extension>
    <channels>2</channels>
  </format>
  <external>
    <command>waon/waon</command>
    <arguments>%OPTIONS -i %INFILE -o %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>

=== barracuda156/BoCA/bin64/boca_decoder_ffmpeg_atrac3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>ATRAC-3 Decoder</name>
  <version>1.0</version>
  <id>ffmpeg-atrac3-in</id>
  <type>decoder</type>
  <format>
    <name>ATRAC-3 Files</name>
    <extension>aa3</extension>
    <extension>wav</extension>
  </format>
  <format>
    <name>OpenMG Audio Files</name>
    <extension>oma</extension>
    <extension>omg</extension>
  </format>
  <external>
    <command>codecs/cmdline/ffmpeg.exe</command>
    <arguments>-i %INFILE %OPTIONS -f wav %OUTFILE</arguments>
    <mode>file</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== barracuda156/BoCA/bin64/boca_decoder_wavpack.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>WavPack Lossless Decompressor</name>
  <version>1.0</version>
  <id>wv-in</id>
  <type>decoder</type>
  <format>
    <name>WavPack Files</name>
    <extension>wv</extension>
  </format>
  <external>
    <command>codecs/cmdline/wvunpack.exe</command>
    <arguments>%OPTIONS %INFILE -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <tag mode="append">APEv2</tag>
  </external>
</component>

=== barracuda156/BoCA/bin/boca_encoder_ffmpeg_mp2.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>MPEG-1 Audio Layer 2 Encoder</name>
  <version>1.0</version>
  <id>ffmpeg-mp2-out</id>
  <type>encoder</type>
  <format>
    <name>MPEG-1 Audio Layer 2</name>
    <extension>mp2</extension>
  </format>
  <external>
    <command>codecs/cmdline/ffmpeg.exe</command>
    <arguments>-f wav -i %INFILE -acodec mp2 %OPTIONS %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>

=== barracuda156/BoCA/bin64/boca_encoder_mpc.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>Musepack Audio Encoder</name>
  <version>1.0</version>
  <id>mpc-out</id>
  <type>encoder</type>
  <format>
    <name>Musepack Audio Files</name>
    <extension>mpc</extension>
  </format>
  <external>
    <command>codecs/cmdline/mppenc.exe</command>
    <arguments>%OPTIONS - %OUTFILE</arguments>
    <mode>stdio</mode>
    <informat>wave</informat>
    <tag mode="append">APEv2</tag>
    <parameters>
      <range name="Quality" argument="--quality %VALUE" default="5">
	<min alias="poor">0</min>
	<max alias="excellent">10</max>
      </range>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/bin/boca_decoder_la.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>LA Lossless Audio Decoder</name>
  <version>1.0</version>
  <id>la-in</id>
  <type>decoder</type>
  <format>
    <name>LA Audio Files</name>
    <extension>la</extension>
  </format>
  <external>
    <command>codecs/cmdline/la.exe</command>
    <arguments>-cout %OPTIONS %INFILE</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
    <tag mode="append">ID3v1</tag>
  </external>
</component>

=== barracuda156/BoCA/scripts/win32/boca_encoder_aften.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Aften A/52 (AC3) Encoder</name>
  <version>1.0</version>
  <id>aften-out</id>
  <type>encoder</type>
  <format>
    <name>AC3 Files</name>
    <extension>ac3</extension>
  </format>
  <external>
    <command>codecs/cmdline/aften.exe</command>
    <arguments>%OPTIONS %INFILE %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>
