=== barracuda156/BoCA/doc/dtds/component.dtd
<!-- BoCA component XML description DTD -->

<!ENTITY % BoCA.Version "-//DTD BoCA 1.0 Draft//EN">

<!ELEMENT component (name, version, id, type, format*, external?)>

	<!ELEMENT name (#PCDATA)>
	<!ELEMENT version (#PCDATA)>
	<!ELEMENT id (#PCDATA)>
	<!ELEMENT type (#PCDATA)>

	<!ELEMENT format (name, extension+)>

		<!ELEMENT extension (#PCDATA)>

	<!ELEMENT external (command, arguments, mode, (informat?, outformat?), tag*, parameters?)>

		<!ELEMENT command (#PCDATA)>
		<!ELEMENT arguments (#PCDATA)>
		<!ELEMENT mode (#PCDATA)>
		<!ELEMENT informat (#PCDATA)>
		<!ELEMENT outformat (#PCDATA)>

		<!ELEMENT tag (#PCDATA)>
		<!ATTLIST tag mode CDATA #REQUIRED>

		<!ELEMENT parameters (switch | selection | range)*>

			<!ELEMENT switch (#PCDATA)>
			<!ATTLIST switch name	  CDATA	  #REQUIRED
					 argument CDATA	  #REQUIRED
					 enabled  NMTOKEN #IMPLIED>

			<!ELEMENT selection (option+)>
			<!ATTLIST selection name     CDATA   #REQUIRED
					    argument CDATA   #REQUIRED
					    enabled  NMTOKEN #IMPLIED
					    default  NMTOKEN #IMPLIED>

				<!ELEMENT option (#PCDATA)>
				<!ATTLIST option alias CDATA #IMPLIED>

			<!ELEMENT range (min, max)>
			<!ATTLIST range name	 CDATA	 #REQUIRED
					argument CDATA	 #REQUIRED
					enabled	 NMTOKEN #IMPLIED
					default	 NMTOKEN #IMPLIED
					step	 NMTOKEN #IMPLIED>

				<!ELEMENT min (#PCDATA)>
				<!ATTLIST min alias CDATA #IMPLIED>

				<!ELEMENT max (#PCDATA)>
				<!ATTLIST max alias CDATA #IMPLIED>

=== barracuda156/BoCA/scripts/win32/boca_encoder_mareo.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>MAREO Multi Encoder Hub</name>
  <version debug="true">1.0</version>
  <id>mareo-out</id>
  <type>encoder</type>
  <format>
    <name>MAREO Temporary Wave File</name>
    <extension>wav</extension>
  </format>
  <external>
    <command>codecs/cmdline/mareo/mareo.exe</command>
    <arguments>codecs\cmdline\mareo\mareo.ini %INFILE %OUTFILE %ARTIST %ALBUM %TITLE %TRACK %YEAR %GENRE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>

=== barracuda156/BoCA/bin64/boca_encoder_fhg.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>Fraunhofer IIS MP3 Surround Encoder</name>
  <version>1.0</version>
  <id>fhg-out</id>
  <type>encoder</type>
  <format>
    <name>MPEG Audio Layer 3</name>
    <extension>mp3</extension>
  </format>
  <external>
    <command>codecs/cmdline/mp3sEncoder.exe</command>
    <arguments>-eof -if - -of %OUTFILE %OPTIONS</arguments>
    <mode>stdio</mode>
    <informat>wave</informat>
    <tag mode="prepend">ID3v2</tag>
    <parameters>
      <range name="Bitrate" argument="-br %VALUE000" default="192" enabled="true" step="4">
	<min alias="16 kbps">16</min>
	<max alias="320 kbps">320</max>
      </range>
      <selection name="Encoding mode" argument="-m %VALUE" default="0">
	<option alias="CBR">0</option>
	<option alias="VBR highest quality">1</option>
	<option alias="VBR high quality">2</option>
	<option alias="VBR intermediate quality">3</option>
	<option alias="VBR intermediate bitrate">4</option>
	<option alias="VBR low bitrate">5</option>
      </selection>
      <selection name="Encoder quality" argument="-q %VALUE" default="0">
	<option alias="Fast encoding">0</option>
	<option alias="High quality">1</option>
      </selection>
      <switch name="Write VBRI header" argument="-vbri"/>
      <switch name="Downmix to mono" argument="-mono"/>
      <switch name="Use Original File Length" argument="-ofl" enabled="true"/>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/scripts/win32/boca_decoder_alac.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Apple Lossless Decoder</name>
  <version>1.0</version>
  <id>alac-in</id>
  <type>decoder</type>
  <format>
    <name>Apple Lossless Files</name>
    <extension>m4a</extension>
    <tag id="mp4-tag" mode="other">MP4 Metadata</tag>
  </format>
  <external>
    <command>codecs/cmdline/alac.exe</command>
    <arguments>%OPTIONS %INFILE</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== barracuda156/BoCA/scripts/boca_encoder_speex.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.freac.org/boca/component.dtd">
<component>
  <name>Speex Speech Encoder</name>
  <version>1.0</version>
  <id>speexcmd-enc</id>
  <type>encoder</type>
  <format>
    <name>Speex Files</name>
    <extension>spx</extension>
    <tag id="vorbis-tag" mode="other">Vorbis Comment</tag>
  </format>
  <external>
    <command>speexenc</command>
    <arguments>%OPTIONS %INFILE %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
    <parameters>
      <range name="Encoding quality" argument="--quality %VALUE" default="8">
	<min alias="fastest">0</min>
	<max alias="best">10</max>
      </range>
      <switch name="Use VBR mode" argument="--vbr"/>
      <range name="Use ABR mode" argument="--abr %VALUE" default="32">
	<min alias="%1 kbps">8</min>
	<max alias="%1 kbps">64</max>
      </range>
      <switch name="Enable voice activity detection" argument="--vad"/>
      <switch name="Denoise input before encoding" argument="--denoise"/>
      <switch name="Apply adaptive gain control" argument="--agc"/>
    </parameters>
  </external>
</component>

=== barracuda156/BoCA/bin64/boca_decoder_mpc.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>Musepack Audio Decoder</name>
  <version>1.0</version>
  <id>mpc-in</id>
  <type>decoder</type>
  <format>
    <name>Musepack Audio Files</name>
    <extension>mpc</extension>
    <tag mode="append">APEv2</tag>
  </format>
  <external>
    <command>codecs/cmdline/mpcdec.exe</command>
    <arguments>%OPTIONS %INFILE %OUTFILE</arguments>
    <mode>file</mode>
    <outformat>wave</outformat>
  </external>
</component>

=== barracuda156/BoCA/bin/boca_encoder_flake.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>Flake FLAC Encoder</name>
  <version>1.0</version>
  <id>flake-out</id>
  <type>encoder</type>
  <format>
    <name>FLAC Audio Files</name>
    <extension>flac</extension>
  </format>
  <external>
    <command>codecs/cmdline/flake.exe</command>
    <arguments>%OPTIONS %INFILE -o %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>

=== barracuda156/BoCA/bin/boca_encoder_ffmpeg_alac.1.0.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>Apple Lossless Encoder</name>
  <version>1.0</version>
  <id>ffmpeg-alac-out</id>
  <type>encoder</type>
  <format>
    <name>Apple Lossless Files</name>
    <extension>m4a</extension>
    <tag mode="other">MP4Metadata</tag>
  </format>
  <external>
    <command>codecs/cmdline/ffmpeg.exe</command>
    <arguments>-f wav -i %INFILE -acodec alac %OPTIONS %OUTFILE</arguments>
    <mode>file</mode>
    <informat>wave</informat>
  </external>
</component>

=== barracuda156/BoCA/scripts/win32/boca_decoder_ffmpeg_realaudio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE component SYSTEM "http://www.bonkenc.org/boca/component.dtd">
<component>
  <name>RealAudio Decoder</name>
  <version>1.0</version>
  <id>ffmpeg-realaudio-in</id>
  <type>decoder</type>
  <format>
    <name>RealAudio Files</name>
    <extension>ra</extension>
  </format>
  <external>
    <command>codecs/cmdline/ffmpeg.exe</command>
    <arguments>-i %INFILE %OPTIONS -f wav -</arguments>
    <mode>stdio</mode>
    <outformat>wave</outformat>
  </external>
</component>
